POST {{baseUrl}}/cocktails
content-type: application/json

{
    "name": "Virgin Mojito",
    "category": "Non-Alcoholic",
    "instructions": "Just water",
    "isAlcoholic": false,
    "ingredients": [{
      "ingredientId": 2,
      "amount": "50",
      "unit": "ml",
      "orderIndex": 1
    }]
}

###

GET {{baseUrl}}/cocktails

###

GET {{baseUrl}}/cocktails/1

###

PATCH {{baseUrl}}/cocktails/1
content-type: application/json

{
  "name": "Updated Mojito"
}

###

DELETE {{baseUrl}}/cocktails/1
